describe("Celeri Challenge", () => {


    it('Visit Celeri', () => {
        cy.viewport(1440, 900)
        const fotoAdjuntar = "blankphoto.jpg"
        cy.visit("https://product-onboarding.vercel.app/")
        cy.get('.css-uxaz7x').click()
        cy.get('[aria-label="Agregar nuevo"] > .MuiButton-root').click()
        cy.wait(3000)
        /////TITULARES
        //Datos generales
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(1) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("DNI", "{enter}")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type(9999)
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(3)').type("CUIT", "{enter}")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(4)').type(11111111111)
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type("Guido")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type("Test")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("Sejas")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type("Argentina", "{enter}")
        cy.get('.MuiGrid-container > :nth-child(9)').type("31/05/2000")
        cy.get(':nth-child(10) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Masculino")
        cy.get("li").contains("Masculino").click()
        cy.get(':nth-child(11) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Soltero")
        cy.get("li").contains("Soltero").click()
        //Dato de contacto
        cy.get(':nth-child(2) > :nth-child(2) > .MuiGrid-container > :nth-child(1)').type("test@yopmail.com")
        cy.get(':nth-child(2) > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type(1111111111)
        //Dirección legal
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(1)').type("Argentina")
        cy.get("li").contains("Argentina").click()
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type("Ciudad Autonoma de Buenos Aires")
        cy.get("li").contains("Ciudad Autonoma de Buenos Aires").click()
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > .MuiGrid-grid-lg-4').type("Calle Falsa")
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type(123)
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type(10)
        cy.get(':nth-child(3) > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("A")
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type(1111)
        cy.get('.MuiCheckbox-root > .PrivateSwitchBase-input').check()
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(1) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Argentina")
        cy.get("li").contains("Argentina").click()
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(2) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Ciudad Autonoma de Buenos Aires")
        cy.get("li").contains("Ciudad Autonoma de Buenos Aires").click()
        //Dirección real
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > .MuiGrid-grid-lg-4').type("Calle Real")
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type(321)
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type(10)
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("B")
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type(2222)
        //Datos laborales e impositivos
        cy.get(':nth-child(4) > :nth-child(2) > .MuiGrid-container > .MuiGrid-root').type("Jubilado")
        cy.get("li").contains("Jubilado").click()
        //Declaraciones juradas
        cy.get(':nth-child(1) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        cy.get(':nth-child(2) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        cy.get(':nth-child(3) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        //Finalización
        cy.get('.justify-end > .MuiButton-contained').click()
        /////CUENTAS BANCARIAS
        cy.get(':nth-child(2) > .flex > [aria-label="Agregar nuevo"] > .MuiButton-root').click()
        cy.get('.MuiGrid-grid-md-8').type("0534919911100068441488")
        cy.wait(3000)
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get('.MuiGrid-container > :nth-child(2)').type("Test.alias")
        cy.get('.MuiGrid-container > :nth-child(3)').type("Banco Galicia")
        cy.get("li").contains("Banco Galicia").click()
        cy.get('.MuiGrid-container > :nth-child(4)').type("Caja De Ahorro")
        cy.get("li").contains("Caja De Ahorro").click()
        cy.get('.MuiGrid-container > :nth-child(5)').type("ARS - Pesos Argentinos")
        cy.get("li").contains("ARS - Pesos Argentinos").click()
        cy.get('.justify-end > .MuiButton-contained').click()
        /////PERFIL DEL INVERSOR
        cy.get('.flex > .MuiButton-root > .MuiButton-endIcon > .material-icons').click()
        cy.get(':nth-child(1) > .MuiFormControl-root > .MuiFormGroup-root').contains("Algo").click()
        cy.get(':nth-child(2) > .MuiFormControl-root > .MuiFormGroup-root').contains("Alto").click()
        cy.get(':nth-child(3) > .MuiFormControl-root > .MuiFormGroup-root').contains("Sí").click()
        cy.get(':nth-child(4) > .MuiFormControl-root > .MuiFormGroup-root').contains("Sí").click()
        cy.get('.MuiButton-contained').click()
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        /////PAGINA DE INICIO
        cy.wait(2000)
        cy.get('.PrivateSwitchBase-input').check({ force: true })
        cy.get("button").contains("Abrir Cuenta").click()
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        ////Apertura de cuenta
        cy.get(':nth-child(2) > .MuiPaper-root > .w-full.flex > .flex').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(3) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(4) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(5) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.wait(2000)
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
    });

    it("Version Mobile", () => {
        cy.viewport(414, 896)
        const fotoAdjuntar = "blankphoto.jpg"
        cy.visit("https://product-onboarding.vercel.app/")
        cy.get('.css-uxaz7x').click()
        cy.get('[aria-label="Agregar nuevo"] > .MuiButton-root').click()
        cy.wait(3000)
        /////TITULARES
        //Datos generales
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(1) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("DNI", "{enter}")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type(9999)
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(3)').type("CUIT", "{enter}")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(4)').type(11111111111)
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type("Guido")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type("Test")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("Sejas")
        cy.get('.px-16 > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type("Argentina", "{enter}")
        cy.get('.MuiGrid-container > :nth-child(9)').type("31/05/2000")
        cy.get(':nth-child(10) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Masculino")
        cy.get("li").contains("Masculino").click()
        cy.get(':nth-child(11) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Soltero")
        cy.get("li").contains("Soltero").click()
        //Dato de contacto
        cy.get(':nth-child(2) > :nth-child(2) > .MuiGrid-container > :nth-child(1)').type("test@yopmail.com")
        cy.get(':nth-child(2) > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type(1111111111)
        //Dirección legal
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(1)').type("Argentina")
        cy.get("li").contains("Argentina").click()
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(2)').type("Ciudad Autonoma de Buenos Aires")
        cy.get("li").contains("Ciudad Autonoma de Buenos Aires").click()
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > .MuiGrid-grid-lg-4').type("Calle Falsa")
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type(123)
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type(10)
        cy.get(':nth-child(3) > :nth-child(1) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("A")
        cy.get(':nth-child(3) > .mb-16 > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type(1111)
        cy.get('.MuiCheckbox-root > .PrivateSwitchBase-input').check()
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(1) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Argentina")
        cy.get("li").contains("Argentina").click()
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(2) > .flex > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root').type("Ciudad Autonoma de Buenos Aires")
        cy.get("li").contains("Ciudad Autonoma de Buenos Aires").click()
        //Dirección real
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > .MuiGrid-grid-lg-4').type("Calle Real")
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(5)').type(321)
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(6)').type(10)
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(7)').type("B")
        cy.get(':nth-child(3) > :nth-child(2) > .MuiGrid-container > :nth-child(8)').type(2222)
        //Datos laborales e impositivos
        cy.get(':nth-child(4) > :nth-child(2) > .MuiGrid-container > .MuiGrid-root').type("Jubilado")
        cy.get("li").contains("Jubilado").click()
        //Declaraciones juradas
        cy.get(':nth-child(1) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        cy.get(':nth-child(2) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        cy.get(':nth-child(3) > .MuiFormControl-root > .MuiFormGroup-root').contains("No").click()
        //Finalización
        cy.get('.justify-end > .MuiButton-contained').click()
        /////CUENTAS BANCARIAS
        cy.get(':nth-child(2) > .MuiGrid-root > .items-center > [aria-label="Agregar nuevo"] > .MuiButton-root > .MuiButton-endIcon > .material-icons').click()
        cy.get('.MuiGrid-grid-md-8').type("0534919911100068441488")
        cy.wait(3000)
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get('.MuiGrid-container > :nth-child(2)').type("Test.alias")
        cy.get('.MuiGrid-container > :nth-child(3)').type("Banco Galicia")
        cy.get("li").contains("Banco Galicia").click()
        cy.get('.MuiGrid-container > :nth-child(4)').type("Caja De Ahorro")
        cy.get("li").contains("Caja De Ahorro").click()
        cy.get('.MuiGrid-container > :nth-child(5)').type("ARS - Pesos Argentinos")
        cy.get("li").contains("ARS - Pesos Argentinos").click()
        cy.get('.justify-end > .MuiButton-contained').click()
        /////PERFIL DEL INVERSOR
        cy.get('.items-center > .MuiButton-root > .MuiButton-endIcon > .material-icons').click()
        cy.get(':nth-child(1) > .MuiFormControl-root > .MuiFormGroup-root').contains("Algo").click()
        cy.get(':nth-child(2) > .MuiFormControl-root > .MuiFormGroup-root').contains("Alto").click()
        cy.get(':nth-child(3) > .MuiFormControl-root > .MuiFormGroup-root').contains("Sí").click()
        cy.get(':nth-child(4) > .MuiFormControl-root > .MuiFormGroup-root').contains("Sí").click()
        cy.get('.MuiButton-contained').click()
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        /////PAGINA DE INICIO
        cy.wait(2000)
        cy.get('.PrivateSwitchBase-input').check({ force: true })
        cy.get("button").contains("Abrir Cuenta").click()
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        ////Apertura de cuenta
        cy.get(':nth-child(2) > .MuiPaper-root > .w-full.flex > .flex').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(3) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(4) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.get(':nth-child(5) > .MuiPaper-root > .w-full.flex > .flex > .MuiButton-root').click()
        cy.get('.dropzone').click().then(() => {
            cy.get("input[type='file']").attachFile(fotoAdjuntar)
        })
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
        cy.wait(2000)
        cy.get('.MuiDialogActions-root > .MuiButton-contained').click()
    })
})